

export { default as Location } from './Location'
export { default as BusinessTime } from './BusinessTime'
export { default as FillHeart } from './FillHeart'
export { default as OutlineHeart } from './OutlineHeart'
export { default as Eye } from './Eye'
export { default as Map } from './Map'
export { default as Close } from './Close'
export { default as Bar } from './Bar'
export { default as Search } from './Search'
export { default as Diamond } from './Diamond'
export { default as Facebook } from './Facebook'
export { default as YouTube } from './YouTube'
export { default as Twitter } from './Twitter'
export { default as Instagram } from './Instagram'
export { default as Telegram } from './Telegram'
export { default as Phone } from './Phone'
export { default as ScreenPhone } from './ScreenPhone'
export { default as Email } from './Email'
export { default as Earth } from './Earth'
export { default as Plus } from './Plus'
export { default as ThreeDots } from './ThreeDots'
export { default as CgSmartphoneRam } from './SmartphoneRam'
export { default as FaBath } from './Bath'
export { default as FaBed } from './Bed'
export { default as Memory } from "./Memory"
export { default as Squares } from "./Squares"
export { default as Calendar } from "./Calendar"
export { default as Share } from "./Share"
export { default as Star } from "./Star"
export { default as StarFill } from "./StarFill"
export { default as StarHalf } from "./StarHalf"
export { default as Report } from "./Report"
export { default as CheckCircleFill } from "./CheckCircleFill"
export { default as Pin } from "./pin"
export { default as Iconmore } from "./iconmore"
export { default as World } from "./World"
export { default as Filtericon } from "./filter"
export { default as Upload } from "./Upload"
export { default as CircleClose } from "./CircleClose"
export { default as User } from "./User"
export { default as Setting } from "./Setting"
export {default as Position} from"./Position"